### ISSUE TITLE
How to run???

### ISSUE THREAD

**Issue by IamOmaR22** [bchiang7/octoprofile#14]
Please provide the full instruction for running it

**Comment by rishikesh2003** [comment]
Could you be more certain, if you want to run this on our local machine or you want to find your profile?

**Comment by bchiang7** [comment]
Can you be more specific? I'm not sure what your question is. To run the app locally, simply follow the two steps in the [Getting Started section](https://github.com/bchiang7/octoprofile#getting-started) of the readme

**Comment by IamOmaR22** [comment]
I want to run this on my local machine and with my profile

**Comment by bchiang7** [comment]
1. Install dependencies: `yarn`
2. Start the local server: `npm run dev`
3. Open localhost:3000, type your username into the input, and hit enter

**Comment by IamOmaR22** [comment]
Thanks
